import React, { useState } from 'react';
import { calculateTimeWithAI } from '../services/geminiService';
import { formatTime } from '../utils/timeUtils';
import { Sparkles, Send, Loader2, AlertCircle } from 'lucide-react';
import { AiCalculationResponse } from '../types';

const AICalculator: React.FC = () => {
  const [input, setInput] = useState('');
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<AiCalculationResponse | null>(null);
  const [error, setError] = useState<string | null>(null);

  const handleCalculate = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!input.trim()) return;

    setLoading(true);
    setError(null);
    setResult(null);

    try {
      const currentTime = formatTime(new Date());
      const response = await calculateTimeWithAI(input, currentTime);
      setResult(response);
    } catch (err) {
      setError("Sorry, I couldn't understand that time calculation. Please try again.");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="w-full max-w-2xl mx-auto">
      <div className="bg-slate-800 rounded-2xl border border-slate-700 shadow-xl overflow-hidden">
        <div className="p-6 md:p-8 space-y-6">
          <div className="flex items-start gap-4">
            <div className="p-3 bg-gradient-to-br from-purple-500 to-indigo-600 rounded-xl shadow-lg">
              <Sparkles className="text-white" size={24} />
            </div>
            <div>
              <h3 className="text-xl font-bold text-white">AI Time Assistant</h3>
              <p className="text-slate-400 text-sm mt-1">
                Ask naturally like "What time is it in 90 minutes?" or "Add 3 hours and 15 mins to 14:30"
              </p>
            </div>
          </div>

          <form onSubmit={handleCalculate} className="relative">
            <input
              type="text"
              value={input}
              onChange={(e) => setInput(e.target.value)}
              placeholder="e.g., Add 45 minutes to now..."
              className="w-full bg-slate-900/50 text-white placeholder-slate-500 text-lg p-5 pr-14 rounded-xl border border-slate-600 focus:border-purple-500 focus:ring-2 focus:ring-purple-500/50 outline-none transition-all"
            />
            <button
              type="submit"
              disabled={loading || !input.trim()}
              className="absolute right-3 top-1/2 -translate-y-1/2 p-2 bg-purple-600 text-white rounded-lg hover:bg-purple-500 disabled:opacity-50 disabled:hover:bg-purple-600 transition-colors"
            >
              {loading ? <Loader2 className="animate-spin" size={20} /> : <Send size={20} />}
            </button>
          </form>

          {error && (
            <div className="flex items-center gap-3 p-4 bg-red-900/20 border border-red-900/50 rounded-lg text-red-200">
              <AlertCircle size={20} />
              <p>{error}</p>
            </div>
          )}

          {result && (
            <div className="animate-in fade-in slide-in-from-bottom-4 duration-500">
               <div className="relative overflow-hidden bg-gradient-to-br from-slate-900 to-purple-900/40 border border-purple-500/30 rounded-xl p-6 flex flex-col items-center text-center">
                 <div className="absolute top-0 left-0 w-full h-1 bg-gradient-to-r from-purple-500 to-indigo-500"></div>
                 
                 <span className="text-slate-400 text-xs font-semibold uppercase tracking-wider mb-2">
                   {result.explanation}
                 </span>
                 
                 <div className="text-6xl font-bold text-white font-mono tracking-tighter mb-2">
                   {result.resultingTime}
                 </div>
                 
                 {/* Updated the model name in UI to reflect the actual model being used */}
                 <div className="text-xs text-purple-300/70 font-medium">
                   Generated by Gemini 3 Flash
                 </div>
               </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default AICalculator;